### ISSUE TITLE
galactic release

### ISSUE THREAD

**Issue by wep21** [astuff/pacmod3_msgs#6] opened 2021-10-20 05:57 UTC
@icolwell-as Do you have any plan to release new distro(`galactic` and `rolling`) ?

**Comment by icolwell-as** [comment] 2021-10-20 14:15
Hi @wep21, we won't be releasing to rolling since we don't distribute this package via the ROS buildfarm. We distribute from our own apt repo. See install instructions for more details: https://github.com/astuff/pacmod3_msgs#installation

Regarding galactic release, we generally don't support short-term ROS releases (`galactic`), and try to focus on the LTS releases only (foxy, new H-turtle release in 2022). That being said, we could consider releasing this on Galactic if there is enough demand. Is there something specific about Galactic that you absolutely need? or would you be able to wait until H-turtle is released in 7 months?

**Comment by wep21** [comment] 2021-10-20 15:06
@icolwell-as
> Is there something specific about Galactic that you absolutely need?

Yes, there are some performance issues about `foxy`, e.g. rclcpp, dds, rosbag2, so we are now developing basically on `galactic`.
It is preferable that pacmod3-related packages are available from your repository for the convenience.

**Comment by icolwell-as** [comment] 2021-10-22 14:15
Ok sounds good, I'll see what I can release in the next couple of weeks. What packages are you specifically interested in?
I assume `pacmod3_msgs` and the `pacmod3` driver? Do you also need `kvaser_interface`, or do you use socketcan?

**Comment by wep21** [comment] 2021-10-23 14:12
Thank you for your consideration. I need `pacmod3_msgs`, `pacmod3` and also `kvaser_interface` .

**Comment by icolwell-as** [comment] 2021-11-10 16:00
@wep21, the requested ROS packages have been released on Galactic via our apt repo, see the README for each repo/package for installation instructions if you aren't already familiar.

**NOTE**: Since Galactic is not an LTS release, we don't test these packages in-vehicle on Galactic or guarantee any support for them. Please test at your own risk with caution.

Let us know if you have any issues with them, they are the same version as is currently released on Foxy, so I don't anticipate any functional differences.

**Closed as completed by icolwell-as** 2021-11-10 16:00 UTC

**Comment by kenji-miyake** [comment] 2022-01-08 20:49
@icolwell-as Hello, it seems Galactic ARM version isn't released.
https://s3.amazonaws.com/autonomoustuff-repo

Is it possible to release the version as well?

**Comment by icolwell-as** [comment] 2022-01-11 14:39
Sure, ARM64 I assume?

**Comment by wep21** [comment] 2022-01-13 07:42
@icolwell-as Yes, please.

**Comment by kenji-miyake** [comment] 2022-01-13 09:00
@icolwell-as Yes, thank you very much! (Thank you @wep21 as well, I overlooked.)

**Comment by icolwell-as** [comment] 2022-01-13 17:33
@kenji-miyake, @wep21 , the 3 packages have been released for ARM64.

Same disclaimer as before:

> Since Galactic is not an LTS release, we don't test these packages in-vehicle on Galactic or guarantee any support for them. Please test at your own risk with caution.

Let me know if you have any issues with using them.

**Comment by kenji-miyake** [comment] 2022-01-14 01:09
Confirmed, thank you!
![image](https://user-images.githubusercontent.com/31987104/149433815-d2d4fc9e-54fd-4a2d-8b6e-3407b09d1489.png)

> Same disclaimer as before:

Yes, of course. :smile:
